name: build
on:
  push:
    branches:
      - main
  #pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: install python3
        run: sudo apt install python3-pip
        
      - name: install pip install black, isort, flake8
        run: |
          pip install black
          pip install isort
          pip install flake8
    
#       - name: black, isort,  chek files with flag
#         run: black --diff .
        
        
      - name: isort check 
        run: isort . --diff
      
#       - name: flake8 check
#         run: flake8 --extend-ignore E203,W234 .
          
          
        
          
        
      
        
